import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const mont = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Indusrify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mont.className} >
        <Navbar />

        {children}
        <Footer />
      </body>
    </html>
  );
}
